### ISSUE TITLE
No status values being returned

### ISSUE THREAD

**Issue by Collin-Sanders** [gogades/hass-infinitive#13]
This is a similar issue as the closed issue #9 except that I can see that there are data values being returned by the infinitive front end:

![image](https://user-images.githubusercontent.com/54324382/162465467-0e679797-07e8-4a07-b363-a7a070f2f7b3.png)

They just dont show up in my HA installation:

![image](https://user-images.githubusercontent.com/54324382/162465755-089dca16-9766-4955-b88b-756b8d912791.png)

Home Assistant 2022.4.1
Version core-2022.4.1 
Version supervisor-2022.03.5 
Operating System Home Assistant OS 7.6 

Is there any way I can get these values to show up properly?

TYIA!

**Comment by mww012** [comment]
That's interesting. I'll need a little more info before we can really dive in. 

1. What version of the HA Infinitive version are you running?

2. When you installed Infinitive itself, what repo did you pull from?  Was it from acd or will1604?

**Comment by Collin-Sanders** [comment]
I am running HA Infinitive version 0.0.9 and I used the acd repo for the server. For the time being I am using an iframe to insert the thermostat controls.

**Comment by mww012** [comment]
Ah ok. There's the issue. Will1604 forked the acd repo and added a a few extra things as well as re-organized the API. 

I bet things will settled for you if you build that one.

**Comment by Collin-Sanders** [comment]
I wiped my SD card and followed the installation instructions here: https://github.com/Will1604/infinitive and I am still having the same issue. Any suggestions?

**Comment by bbarnes11** [comment]
you need to build mww012's infinitive fork

I had the same issues b/c i was using the built executable from ACD.  When I saw the instructions to rebuild infinitive using go from mww012's fork, it seemed unnecessary. However, ACDs build doesn't work quite right with the home assistant integration.  I got the same results as you.  Further, the instructions from Will1604's fork just list the same wget command which downloads ACDs infinitive executable, so that wont help you.

The instructions below are what you need to do (update the go version):

`wget https://go.dev/dl/goX.XX.linux-amd64.tar.gz`
`rm -rf /usr/local/go && tar -C /usr/local -xzf go1.19.linux-amd64.tar.gz`
`export PATH=$PATH:/usr/local/go/bin`
`go install github.com/mww012/infinitive@latest`

After rebuilding the executable I had proper values being pulled from infinitive

**Comment by Collin-Sanders** [comment]
This resolved the issue!!

https://go.dev/dl/ - Latest go version (For raspberry pi you will want the ARMV6 version)

wget https://go.dev/dl/<REPLACE WITH THE LATEST ARMV6 VERSION NAME>
rm -rf /usr/local/go && tar -C /usr/local -xzf <REPLACE WITH THE LATEST ARMV6 VERSION NAME>
export PATH=$PATH:/usr/local/go/bin
go install github.com/mww012/infinitive@latest

nano /lib/systemd/system/infinitive.service
- Update this line: ExecStart=/root/go/bin/infinitive -httpport=8080 -serial=/dev/ttyUSB0

systemctl daemon-reload
systemctl restart infinitive.service
systemctl status infinitive.service
