### ISSUE TITLE
Infinitive integration broken 

### ISSUE THREAD

**Issue by barrys2** [gogades/hass-infinitive#15]
Has anyone else experienced the infinitive integration not working?  Everything was fine until a few days ago.  I can confirm that my PI and serial adapter are functioning because I can see all values using the Browder UI.

**Comment by rfmcmanus** [comment]
No issues here, running rpi4 with
Home Assistant 2023.8.4
Supervisor 2023.08.3
Operating System 10.5
Frontend 20230802.1

Get BlueMail for Android<https://bluemail.me>
On Sep 13, 2023, at 12:46 PM, barrys2 ***@***.******@***.***>> wrote:

Has anyone else experienced the infinitive integration not working? Everything was fine until a few days ago. I can confirm that my PI and serial adapter are functioning because I can see all values using the Browder UI.

**Comment by rfmcmanus** [comment]
Just reading the 2023.9 HA release news.  Talks about changes to the climate entity dialogs. I have not explored the detail.  Any chance you updated to 2023.9.  I am still on 2023.8.4.

**Comment by barrys2** [comment]
Yes I'm running 2023.9.2.  Probably has something to do with it as MyQ
garage door integration is also broken but there has been some discussion
about that I see.

**Comment by barrys2** [comment]
I just updated HA and restarted and all is well other than my garage door
integration.   So i guess this issue can be closed.   Thanks.
